### ISSUE TITLE
Unable to generate full include paths for Unreal Engine

### ISSUE THREAD

**Issue by ikrima** [CoatiSoftware/vs-sourcetrail#49]
Hi,
I was wondering if this can be used on UE4? I saw the previous issue on this was closed as fixed (https://github.com/CoatiSoftware/vs-sourcetrail/issues/7) but currently tried it and I received lots of fatal errors when indexing saying it couldn't find various headers. 

Thanks

**Comment by egraether** [comment]
Which headers are not found? UE4 ones or Standard C++/Compiler ones?

**Comment by ikrima** [comment]
The UE4 ones along with our game project headers and all the UE4 generated headers. IIRC, UBT's around 4.20 changed what it included by default (eg Engine\Classes or Engine\Private) so not sure if that affected the plugin (details here: https://twitter.com/kantandev/status/1020017126806032384)

Thanks for the quick reply!

**Comment by mlangkabel** [comment]
Hi @ikrima, if you are using the Visual Studio extension to export the Compilation Database of the project and Sourcetrail fails when building an index based on this exported database, the first step would be to make sure, that the Visual Studio project is valid. 

So lets start there: Can you build the VS projects (the ones that you marked for generating a CDB) in Visual Studio?

**Comment by mlangkabel** [comment]
Thanks for the update. I wanted to try to reproduce your issue but couldn't find the UnrealEnginePython folder anywhere in the EpicGames/UnrealEngine GitHub repo. 

However, we already have some experience with exporting a Compilation Database from an NMake project:
If VS can build it correctly that only means that the NMake part of the project is configured correctly. But if you open the VS project's properties, and head to the NMake tab, you see "general options" (used for building) and "IntelliSense" options (used for IntelliSense). 
Sourcetrail uses the IntelliSense options to generate the compile commands file, because one cannot just parse NMake to derive all the options. Instead one would need to run it.

So to get to the point: If Visual Studio's IntelliSense can find something it should also work in Sourcetrail. Can you please open the file that contains the `#include "UnrealEnginePython.h"` line in VS, rightclick that line and select the `Open Document "UnrealEnginePython.h"` option.

Please tell if VS is able to open that file.

**Comment by ikrima** [comment]
Ah, that's a plugin in our specific game but I've hit the same issue from the mainline engine branch.

Intellisense does go to the right header file when using go to def/open header file on the include directive line.

Perhaps there are some other settings that are needed? I usually have intellisense and most VS features disabled bc it's painfully slow on large projects (Visual Assist for code completion/grepping). Does that help ring a bell on what would be needed to turn on? I bring it up just bc I had to enable the source browser generation for the vs-sourcetrail extension

**Comment by mlangkabel** [comment]
Are you referring to this issue #41?

If you just generate a Compilation Database for that one project, does it specify and header search paths?

**Comment by ikrima** [comment]
Hmm, I tried force regenerating the intellisense + turning on generate debug info for generated files and that seems to work for the vanilla UE4 build. However, trying to do the same with a project, still fails. Maybe for a baseline, could you try to generate with the ShooterGame project? (https://docs.unrealengine.com/en-us/Resources/SampleGames/ShooterGame)

That sample project contains enough complexity that if you could get that working end to end, I can work backwards.

Thanks again for looking into this. Sourcetrail looks super useful and a couple of us on the gamedev slack have all tried to get UE4's build system working with it

**Comment by mlangkabel** [comment]
I have tried to set up the Unreal Engine and the ShooterGame, as you suggested. After generating the VS project for the ShooterGame, I tried to build it using VS2017, but ended up with a lot of errors like this one:
```
1>C:\sourcetrail\projects\2019_02_21_unreal_shooter\Intermediate\Build\Win64\UE4Editor\Inc\ShooterGame\ShooterPlayerController.generated.h(328): error C2007: #define-Syntax
```

However, generating a compilation database (using the Sourcetrail VS extension) works and when trying to index the project with Sourcetrail based on the generated compile commands, I just get lots of normal errors and no fatal ones. So at least it looks like all the #include directives have been resolved.

**Comment by ikrima** [comment]
Thanks; i think the issue might be with local machine configuration.

**Comment by mlangkabel** [comment]
@ikrima: Do you mean that it works with your project? Or that I should try with a clean VS install?

**Comment by ikrima** [comment]
Seems to work fine with a blank clean install of UE4 on a blank install of VS (i tried it on a cleanly imaged VM with shooter game and it worked).

Still doesn't work for our project so I'd need to do more investigation when I get some free time (could be VS misconfiguration, our customizations of engine project setup/etc)
